Metatavu/vp-kuljetus-vehicle-management-service-api

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/system/SystemApiImpl.kt
- src/native-test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/NativeSystemTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/SystemTestIT.kt
https://github.com/Metatavu/vp-kuljetus-vehicle-management-service-api/issues/18
> ping andpoint and test

- build.gradle.kts
- gradle.properties
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/rest/AbstractApi.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/towables/Towable.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/towables/TowableController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/towables/TowableRepository.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/towables/TowableTranslator.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/towables/TowablesApiImpl.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/Truck.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TruckController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TruckRepository.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TruckTranslator.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TrucksApiImpl.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/vehicles/VehicleTranslator.kt
- src/main/resources/db/changeLog.xml
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TowableTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TruckTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/VehicleTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/impl/InvalidTestValues.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/impl/TowablesTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/impl/TrucksTestBuilderResource.kt
https://github.com/Metatavu/vp-kuljetus-vehicle-management-service-api/issues/23
> Feature 23 metadata

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TruckTranslator.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TruckTelematicDataTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TruckTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/impl/InvalidTestValues.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/impl/TrucksTestBuilderResource.kt
https://github.com/Metatavu/vp-kuljetus-vehicle-management-service-api/issues/32
> optional active vehicle id

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/towables/TowableRepository.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/PublicTruckTranslator.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/PublicTrucksApiImpl.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TruckRepository.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/vehicles/VehicleRepository.kt
- src/native-test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/NativePublicTruckTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/PublicTruckTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/auth/TestBuilderAuthentication.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/impl/PublicTrucksTestBuilderResource.kt
https://github.com/Metatavu/vp-kuljetus-vehicle-management-service-api/issues/34
> Feature 34 public truck info

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/drivercards/DriverCard.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/drivercards/DriverCardApiImpl.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/drivercards/DriverCardController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/drivercards/DriverCardRepository.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/drivercards/DriverCardTranslator.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/rest/AbstractApi.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/telematics/TelematicsApiImpl.kt
- src/main/resources/db/changeLog.xml
- src/native-test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/NativeDriverCardTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/DriverCardTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TestBuilder.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TruckTelematicDataTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/auth/TestBuilderAuthentication.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/impl/DriverCardTestBuilderResource.kt
https://github.com/Metatavu/vp-kuljetus-vehicle-management-service-api/issues/36
> Feature 36 update driver card

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/rest/AbstractApi.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TruckController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TrucksApiImpl.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/truckspeed/TruckSpeed.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/truckspeed/TruckSpeedController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/truckspeed/TruckSpeedRepository.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/truckspeed/TruckSpeedTranslator.kt
- src/main/resources/db/changeLog.xml
- src/native-test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/NativeTruckSpeedTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TruckSpeedTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/impl/TrucksTestBuilderResource.kt
https://github.com/Metatavu/vp-kuljetus-vehicle-management-service-api/issues/42
> Feature 42 add truck speed endpoints

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/rest/AbstractApi.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TruckController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TrucksApiImpl.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/location/TruckLocation.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/location/TruckLocationController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/location/TruckLocationRepository.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/location/TruckLocationTranslator.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/truckspeed/TruckSpeedController.kt
- src/main/resources/db/changeLog.xml
- src/native-test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/NativeTruckLocationsTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TruckLocationTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/impl/TrucksTestBuilderResource.kt
https://github.com/Metatavu/vp-kuljetus-vehicle-management-service-api/issues/44
> Feature 44 truck location

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/PublicTruckTranslator.kt
> Added ID to PublicTruck translator

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/PublicTrucksApiImpl.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TruckController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TruckRepository.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TrucksApiImpl.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/PublicTruckTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/impl/PublicTrucksTestBuilderResource.kt
https://github.com/Metatavu/vp-kuljetus-vehicle-management-service-api/issues/49
> Feature 49 vin list public trucks filter

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TruckController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TrucksApiImpl.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/drivercards/DriverCard.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/drivestate/TruckDriveState.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/drivestate/TruckDriveStateController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/drivestate/TruckDriveStateRepository.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/drivestate/TruckDriveStateTranslator.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/location/TruckLocation.kt
- src/main/resources/db/changeLog.xml
- src/native-test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/NativeTruckDriveStateTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TruckDriveStateTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/impl/TrucksTestBuilderResource.kt
https://github.com/Metatavu/vp-kuljetus-vehicle-management-service-api/issues/51
> Feature 51 add truck drive state endpoints

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/persistence/AbstractRepository.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TruckTestIT.kt
https://github.com/Metatavu/vp-kuljetus-vehicle-management-service-api/issues/53
> enabled pagination for when one of params is missing

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TrucksApiImpl.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/drivestate/TruckDriveStateController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/location/TruckLocationController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/truckspeed/TruckSpeedController.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TruckDriveStateTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TruckLocationTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TruckSpeedTestIT.kt
https://github.com/Metatavu/vp-kuljetus-vehicle-management-service-api/issues/55
> checks for duplicate data

- src/main/resources/db/changeLog.xml
> Added unique constraint for truck location timestamp + truck id

- src/main/resources/db/changeLog.xml
Resolves #57 for the third time
> Added non unique constraint for truck location timestamp + truck id

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/drivestate/TruckDriveStateRepository.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/location/TruckLocationRepository.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/truckspeed/TruckSpeedRepository.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TruckDriveStateTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TruckLocationTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TruckSpeedTestIT.kt
https://github.com/Metatavu/vp-kuljetus-vehicle-management-service-api/issues/64
> telematic listing in seconds

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/persistence/AbstractRepository.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TruckController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TruckRepository.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TrucksApiImpl.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/PublicTruckTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TruckDriveStateTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TruckLocationTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TruckTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/VehicleTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/impl/TrucksTestBuilderResource.kt
> Support for sorting trucks listing by name or platenumber

- build.gradle.kts
> Added health checks

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/rest/AbstractApi.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/towables/TowablesApiImpl.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/PublicTrucksApiImpl.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TrucksApiImpl.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/vehicles/VehiclesApiImpl.kt
> Changed coroutines to use timeouts

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/rest/AbstractApi.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/towables/TowablesApiImpl.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/PublicTrucksApiImpl.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TrucksApiImpl.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/vehicles/VehiclesApiImpl.kt
> Fixed issue with Vert.x threads

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/event/DriverCardEventConsumer.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/event/TruckDriveStateCreatedConsumer.kt
https://github.com/Metatavu/vp-kuljetus-vehicle-management-service-api/issues/82
> added truck id to DriverWorkEventGlobalEvent

- build.gradle.kts
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TrucksApiImpl.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/drivercards/DriverCard.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/drivercards/DriverCardController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/drivercards/DriverCardRepository.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/drivercards/DriverCardTranslator.kt
- src/main/resources/db/changeLog.xml
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/DriverCardTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/settings/DefaultTestProfile.kt
https://github.com/Metatavu/vp-kuljetus-vehicle-management-service-api/issues/84
> Feature 84 driver card management

- openapi/rest-client/api.mustache
- scripts/export-keycloak-config.sh
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/integrations/KeycloakHeaderFactory.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/keycloak/KeycloakAccessToken.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/keycloak/KeycloakClient.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/keycloak/KeycloakIntegrationsClient.kt
- src/main/resources/application.properties
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/resources/wiremock/UserManagementMockTestResource.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/settings/DefaultTestProfile.kt
- src/test/resources/application.properties
- src/test/resources/kc.json
-added Keycloak tokens for UserManagement integrations
-stopped forwarding the headers to rest clients
> Remove API key authentication for service-to-service requests

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TruckController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TrucksApiImpl.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/odometerreading/TruckOdometerReadingController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/odometerreading/TruckOdometerReadingEntity.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/odometerreading/TruckOdometerReadingRepository.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/odometerreading/TruckOdometerReadingTranslator.kt
- src/main/resources/db/changeLog.xml
- src/native-test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/NativeTruckOdometerReadingTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TruckOdometerReadingTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/impl/TrucksTestBuilderResource.kt
https://github.com/Metatavu/vp-kuljetus-vehicle-management-service-api/issues/93
> truck odometer readings implementation

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/location/TruckLocationController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/odometerreading/TruckOdometerReadingController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/truckspeed/TruckSpeedController.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TruckLocationTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TruckOdometerReadingTestIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TruckSpeedTestIT.kt
https://github.com/Metatavu/vp-kuljetus-vehicle-management-service-api/issues/95
> removed extra checks when creating truck events

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/thermometers/ThermometerController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/thermometers/ThermometerEntity.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/thermometers/ThermometerRepository.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/thermometers/ThermometerTranslator.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/thermometers/temperatureReadings/TemperatureReadingEntity.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/thermometers/temperatureReadings/TemperatureReadingRepository.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/thermometers/temperatureReadings/TemperatureReadingsApiImpl.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/thermometers/temperatureReadings/TemperatureTranslator.kt
- src/main/resources/db/changeLog.xml
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TemperatureReadingsIT.kt
> Feature 100 refine tempreature readings and initial support for terminals

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/thermometers/ThermometerController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/thermometers/ThermometerTranslator.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/thermometers/ThermometersApiImpl.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/thermometers/temperatureReadings/TemperatureReadingController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/thermometers/temperatureReadings/TemperatureReadingsApiImpl.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/thermometers/temperatureReadings/TemperatureTranslator.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TemperatureReadingsIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/impl/TemperatureReadingTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/impl/ThermometersTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/impl/TowablesTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/impl/TrucksTestBuilderResource.kt
> Updated api and model names to match latest generated specs

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TruckController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TruckEntity.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TruckRepository.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TruckTranslator.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TrucksApiImpl.kt
- src/main/resources/db/changeLog.xml
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TruckTestIT.kt
> Cost center

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/thermometers/temperatureReadings/TemperatureReadingController.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TemperatureReadingsIT.kt
> Update messaging service

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/towables/TowablesApiImpl.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TrucksApiImpl.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TemperatureReadingsIT.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/impl/TowablesTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/impl/TrucksTestBuilderResource.kt
> Filter trucks and towables by thermometer

- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/thermometers/ThermometerController.kt
- src/main/kotlin/fi/metatavu/vp/vehiclemanagement/thermometers/temperatureReadings/TemperatureReadingController.kt
- src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/TemperatureReadingsIT.kt
> Do not crash for duplicate thermometers
